# Simple workflow for deploying static content to GitHub Pages
name: GPT_DEPLOY

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Prevents concurrent deployments
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci # Ensures dependencies are installed using the package-lock.json file

      # Step 4: Build the project
      - name: Build project
        run: npm run build # Uses the "build" script in your package.json

      # Step 5: Upload build artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist

  deploy:
      runs-on: ubuntu-latest
      needs: build-and-deploy
      permissions:
        pages: write
        id-token: write
      steps:
        # Step 6: Deploy to GitHub Pages
        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v2
          with:
            artifact_name: github-pages
    
